---
- name: External Variable
  hosts: mn-node2
  vars_files:
    - user-var.yaml
  tasks:
   - name: To create user {{ users.bjones.u_name }}
     user:
       name: "{{ users['bjones']['u_name'] }}"
       comment: "{{ users['bjones']['f_name'] }} {{ users['bjones']['l_name'] }}"
       create_home: yes
       home: "{{ users['bjones']['h_dir'] }}"
       password: "{{ users['bjones']['pass'] | password_hash('sha512') }}"
   - name: To create user "{{ users['acook']['u_name'] }}"
     user:
       name: "{{ users['acook']['u_name'] }}"
       comment: "{{ users['acook']['f_name'] }} {{ users['acook']['l_name'] }}"
       create_home: yes
       home: "{{ users['acook']['h_dir'] }}"
       password: "{{ users['acook']['pass'] | password_hash('sha512') }}"

