- name: Using loop with variable in playbook
  hosts: mn-node2
  vars:
    srv_list:
      - httpd
      - vsftpd
  tasks:
    - name: Start Services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ srv_list }}"
      register: srv_out

    - name: Print output of register variable
      debug:
        var: srv_out
