- name: To configure web services
  hosts: mn-node1
  vars:
    firewall: firewalld
  tasks:
    - name: To include variable
      include_vars: vars/variable.yaml
    - name: To install firewall package
      yum:
        name: "{{firewall}}"
        state: latest
    - name: To start service
      service: 
        name: "{{firewall}}"
        state: started
        enabled: true
    - name: To add port in firewalld
      firewalld:
        port: 80/tcp
        state: enabled
        immediate: true
        permanent: true
    - name: To create index File
      copy:
        dest: "{{web_root}}/index.html"
        content: "{{ansible_fqdn}} {{ansible_default_ipv4.address}}"
