- name: Test playbook
  hosts: mn-node1
  tasks:

    - name: Print value
      debug:
        msg:
          - Usages of include and import

    - name: Include task1
      import_tasks: include_task3.yaml
      vars:
        pkg1: ftp
