---
- name: Use loop
  hosts: mn-node1
  tasks:
    - name: Install package
      yum:
        name:
          - postfix
          - dovecot
        state: latest
      when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")
    
    - name: Install package
      apt:
        name:
          - postfix
          - dovecot
        state: latest
      when: ansible_distribution == "Ubuntu"
    
    - name: Install package
      dnf:
        name:
          - postfix
          - dovecot
        state: latest
      when: (ansible_distribution == "RedHat" or ansible_distribution == "Fedora")
